export enum EInternalActions {
  UNLOCK = "UNLOCK",
  GET_STATE = "GET_INTERNAL_STATE",
  GET_UNLOCK_MESSAGE = "GET_UNLOCK_MESSAGE",
  ADD_ACCOUNT = "ADD_ACCOUNT",
}

export enum EExternalActions {
  UNLOCK = "UNLOCK",
  GET_UNLOCK_MESSAGE = "GET_UNLOCK_MESSAGE",
  GET_STATE = "GET_EXTERNAL_STATE",
  ADD_ACCOUNT = "ADD_ACCOUNT",
  SET_AGE = "SET_AGE",
  GET_AGE = "GET_AGE",
  SET_GIVEN_NAME = "SET_GIVEN_NAME",
  GET_GIVEN_NAME = "GET_GIVEN_NAME",
  SET_FAMILY_NAME = "SET_FAMILY_NAME",
  GET_FAMILY_NAME = "GET_FAMILY_NAME",
  SET_BIRTHDAY = "SET_BIRTHDAY",
  GET_BIRTHDAY = "GET_BIRTHDAY",
  SET_GENDER = "SET_GENDER",
  GET_GENDER = "GET_GENDER",
  SET_EMAIL = "SET_EMAIL",
  GET_EMAIL = "GET_EMAIL",
  SET_LOCATION = "SET_LOCATION",
  GET_LOCATION = "GET_LOCATION",
}
