import {
  PersistenceError,
  VersionedObject,
  VolatileStorageMetadata,
  VolatileStorageKey,
  ERecordKey,
} from "@snickerdoodlelabs/objects";
import { ResultAsync } from "neverthrow";

import { IVolatileCursor } from "@persistence/volatile/IVolatileCursor.js";

export interface IVolatileStorage {
  persist(): ResultAsync<boolean, PersistenceError>;
  clearObjectStore(name: string): ResultAsync<void, PersistenceError>;

  putObject<T extends VersionedObject>(
    schemaKey: ERecordKey,
    obj: VolatileStorageMetadata<T>,
  ): ResultAsync<void, PersistenceError>;
  removeObject<T extends VersionedObject>(
    schemaKey: ERecordKey,
    key: VolatileStorageKey,
  ): ResultAsync<VolatileStorageMetadata<T> | null, PersistenceError>;

  getObject<T extends VersionedObject>(
    schemaKey: ERecordKey,
    key: VolatileStorageKey,
    _includeDeleted?: boolean,
  ): ResultAsync<VolatileStorageMetadata<T> | null, PersistenceError>;
  getCursor<T extends VersionedObject>(
    schemaKey: ERecordKey,
    index?: VolatileStorageKey,
    query?: IDBValidKey | IDBKeyRange,
    direction?: IDBCursorDirection | undefined,
    mode?: IDBTransactionMode,
  ): ResultAsync<IVolatileCursor<T>, PersistenceError>;
  getAll<T extends VersionedObject>(
    schemaKey: ERecordKey,
    index?: VolatileStorageKey,
    query?: IDBValidKey | IDBKeyRange,
  ): ResultAsync<VolatileStorageMetadata<T>[], PersistenceError>;
  getAllByIndex<T extends VersionedObject>(
    schemaKey: ERecordKey,
    index: VolatileStorageKey,
    query: IDBValidKey | IDBKeyRange,
  ): ResultAsync<VolatileStorageMetadata<T>[], PersistenceError>;
  getAllKeys<T>(
    schemaKey: ERecordKey,
    index?: VolatileStorageKey,
    query?: IDBValidKey | IDBKeyRange,
    count?: number | undefined,
  ): ResultAsync<T[], PersistenceError>;

  /**
   * Returns the actual key for the object (which may be multiples)
   * @param schemaKey
   * @param obj
   * @returns either the actual key value(s) for obj or null if it is an autogenerated key
   */
  getKey(
    schemaKey: ERecordKey,
    obj: VersionedObject,
  ): ResultAsync<VolatileStorageKey | null, PersistenceError>;
}

export const IVolatileStorageType = Symbol.for("IVolatileStorage");
