import {
  AdSignatureMigrator,
  ChainTransactionMigrator,
  ClickDataMigrator,
  EarnedRewardMigrator,
  EBackupPriority,
  EligibleAdMigrator,
  LatestBlockMigrator,
  LinkedAccountMigrator,
  ReceivingAccountMigrator,
  RestoredBackupMigrator,
  SiteVisitMigrator,
  TokenInfoMigrator,
  ERecordKey,
} from "@snickerdoodlelabs/objects";

import { VolatileTableIndex } from "@persistence/volatile/VolatileTableIndex.js";

export const volatileStorageSchema = [
  new VolatileTableIndex(
    ERecordKey.ACCOUNT,
    "sourceAccountAddress",
    false,
    new LinkedAccountMigrator(),
    EBackupPriority.HIGH,
    [["sourceChain", false]],
  ),
  new VolatileTableIndex(
    ERecordKey.TRANSACTIONS,
    "hash",
    false,
    new ChainTransactionMigrator(),
    EBackupPriority.NORMAL,
    [
      ["timestamp", false],
      ["chainId", false],
      ["value", false],
      ["to", false],
      ["from", false],
    ],
  ),
  new VolatileTableIndex(
    ERecordKey.SITE_VISITS,
    VolatileTableIndex.DEFAULT_KEY,
    true,
    new SiteVisitMigrator(),
    EBackupPriority.NORMAL,
    [
      ["url", false],
      ["startTime", false],
      ["endTime", false],
    ],
  ),
  new VolatileTableIndex(
    ERecordKey.CLICKS,
    VolatileTableIndex.DEFAULT_KEY,
    true,
    new ClickDataMigrator(),
    EBackupPriority.NORMAL,
    [
      ["url", false],
      ["timestamp", false],
      ["element", false],
    ],
  ),
  new VolatileTableIndex(
    ERecordKey.LATEST_BLOCK,
    "contract",
    false,
    new LatestBlockMigrator(),
    EBackupPriority.NORMAL,
  ),
  new VolatileTableIndex(
    ERecordKey.EARNED_REWARDS,
    "queryCID",
    false,
    new EarnedRewardMigrator(),
    EBackupPriority.NORMAL,
    [["type", false]],
  ),
  new VolatileTableIndex(
    ERecordKey.ELIGIBLE_ADS,
    ["queryCID", "key"],
    false,
    new EligibleAdMigrator(),
    EBackupPriority.NORMAL,
    [["type", false]],
  ),
  new VolatileTableIndex(
    ERecordKey.AD_SIGNATURES,
    ["queryCID", "adKey"],
    false,
    new AdSignatureMigrator(),
    EBackupPriority.NORMAL,
    [["type", false]],
  ),
  new VolatileTableIndex(
    ERecordKey.COIN_INFO,
    ["chain", "address"],
    false,
    new TokenInfoMigrator(),
    EBackupPriority.DISABLED,
    undefined,
  ),
  new VolatileTableIndex(
    ERecordKey.RESTORED_BACKUPS,
    VolatileTableIndex.DEFAULT_KEY,
    false,
    new RestoredBackupMigrator(),
    EBackupPriority.DISABLED,
    undefined,
  ),
  new VolatileTableIndex(
    ERecordKey.RECEIVING_ADDRESSES,
    "contractAddress",
    false,
    new ReceivingAccountMigrator(),
    EBackupPriority.NORMAL,
  ),
];
