/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20PermitUpgradeable__factory } from "./ERC20PermitUpgradeable__factory";
export { ERC20VotesUpgradeable__factory } from "./ERC20VotesUpgradeable__factory";
