export default {
  INITIAL: "Initial",
  FORGOT: "Forgot",
  SIGN: "Sign",
  BOTTOM_TAB: "Bottom_Tab",
  WALLET: "Wallet",
  IMAGE_CAROUSEL: "Image_Carousel",
  ONBOARDING: "Onboarding",
  STARTER_TOUR: "Starter_Tour",
  STARTER_TOUR2: "Starter_Tour2",
  COMPONENT_TEST: "Component_Test",
  CARD_DETAILS: "Card_Details",
  SETTINGS: "Settings",
  CRYPTO_SETTINGS: "Crypto_Settings",
  PERSONAL_SETTINGS: "Personal_Settings",
  REWARDS_SETTINGS: "Rewards_Settings",
  PERMISSION_SETTINGS: "Permission_Settings",
  HOME: "Home",
  DASHBOARD: "Dashboard",
};
