version: "3.4"

services:
  doodlechain:
    container_name: doodlechain
    env_file: docker-compose.env
    ports:
      - 8545:8569
    image: 'snickerdoodlelabs/devchain:0.0.4'
    networks:
      - internal

  # extension-onboarding:
  #   image: snickerdoodlelabs/extension-onboarding:local
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./packages/extension-onboarding:/app/packages/extension-onboarding
  #   networks:
  #     - internal

  core-iframe:
    container_name: core-iframe
    env_file: docker-compose.env
    image: snickerdoodlelabs/core-iframe:local
    ports:
      - 9010:80
    networks:
      - internal

  web-integration-test:
    container_name: web-integration-test
    env_file: docker-compose.env
    image: snickerdoodlelabs/web-integration-test:local
    ports:
      - 9011:80
    networks:
      - internal

  ipfs:
    image: ipfs/kubo:latest
    ports:
      - 4001:4001 # Swarm
      - 5001:5001 # Api
      - 8080:8080 # Gateway
    volumes:
      - ./.ipfs/ipfs0:/data/ipfs
      - ./.ipfs/export:/export
      - ./scripts/start_ipfs.sh:/start_ipfs
    entrypoint: ["/sbin/tini", "--", "start_ipfs"]
    command: ["daemon", "--migrate=true", "--agent-version-suffix=docker", "--enable-pubsub-experiment"]
    env_file: docker-compose.env
    networks:
      - internal

networks:
  internal:

volumes:
  data:
