version: "3.4"

services:
  doodlechain:
    container_name: doodlechain
    env_file: docker-compose.env
    ports:
      - 8545:8545
    image: 'snickerdoodlelabs/devchain:0.1.0'
    networks:
      - internal

  extension-onboarding:
    env_file: docker-compose.env
    image: snickerdoodlelabs/extension-onboarding:local
    ports:
      - 9001:80
    networks:
      - internal

  core-iframe:
    container_name: core-iframe
    env_file: docker-compose.env
    image: snickerdoodlelabs/core-iframe:local
    ports:
      - 9010:80
    networks:
      - internal

  web-integration-test:
    container_name: web-integration-test
    env_file: docker-compose.env
    image: snickerdoodlelabs/web-integration-test:local
    ports:
      - 9011:80
    networks:
      - internal

  static-web-integration:
    container_name: static-web-integration
    env_file: docker-compose.env
    image: snickerdoodlelabs/static-web-integration:local
    ports:
      - 9012:80
    networks:
      - internal

  ipfs:
    image: ipfs/kubo:latest
    ports:
      - 4001:4001 # Swarm
      - 5001:5001 # Api
      - 8080:8080 # Gateway
    volumes:
      - ./.ipfs/ipfs0:/data/ipfs
      - ./.ipfs/export:/export
      - ./scripts/start_ipfs.sh:/start_ipfs
    entrypoint: [ "/sbin/tini", "--", "start_ipfs" ]
    command:
      [
        "daemon",
        "--migrate=true",
        "--agent-version-suffix=docker",
        "--enable-pubsub-experiment"
      ]
    env_file: docker-compose.env
    networks:
      - internal

networks:
  internal:


volumes:
  data:
