version: "3.4"

services:
  doodlechain:
    container_name: doodlechain
    ports:
      - 8545:8569
    environment:
      NETWORK: dev
    image: 'snickerdoodlelabs/devchain:latest'

  # extension-onboarding:
  #   image: snickerdoodlelabs/extension-onboarding:local
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./packages/extension-onboarding:/app/packages/extension-onboarding
  #   networks:
  #     - internal
      
  ipfs:
    image: ipfs/go-ipfs:release
    ports:
      - "4021:4001" # Swarm
      - "5021:5001" # Api
      - "8088:8080" # Gateway
    volumes:
      - ./.ipfs/ipfs0:/data/ipfs
      - ./.ipfs/export:/export
      - ./packages/development/ipfs-provider/start_ipfs:/start_ipfs
    environment:
      ACCESS_CONTROL_ALLOW_ORIGIN: '["*"]'

networks:
  internal:

volumes:
  data:
