version: "3.4"

services:
  doodlechain:
    container_name: doodlechain
    env_file: docker-compose.env
    ports:
      - 8545:8569
    image: 'snickerdoodlelabs/devchain:latest'

  # extension-onboarding:
  #   image: snickerdoodlelabs/extension-onboarding:local
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./packages/extension-onboarding:/app/packages/extension-onboarding
  #   networks:
  #     - internal
      
  ipfs:
    image: ipfs/kubo:latest
    ports:
      - 4001:4001 # Swarm
      - 5001:5001 # Api
      - 8080:8080 # Gateway
    volumes:
      - ./.ipfs/ipfs0:/data/ipfs
      - ./.ipfs/export:/export
      - ./scripts/start_ipfs.sh:/start_ipfs
    entrypoint: ["/sbin/tini", "--", "start_ipfs"]
    command: ["daemon", "--migrate=true", "--agent-version-suffix=docker", "--enable-pubsub-experiment"]
    env_file: docker-compose.env
    networks:
      - internal

  # ceramic:
  #   image: ceramicnetwork/js-ceramic:2.7.0-rc.2
  #   ports:
  #     - 7007:7007
  #   volumes:
  #     - ./.ceramic/config/daemon.config.json:/root/.ceramic/daemon.config.json
  #     - ./.ceramic/logs:/root/.ceramic/logs
  #     - ./.ceramic/statestore:/root/.ceramic/statestore
  #   env_file: docker-compose.env
  #   networks:
  #     - internal
  #   depends_on:
  #     - ipfs

networks:
  internal:

volumes:
  data:
