/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IContentFactory {
  export type ListingStruct = {
    previous: BigNumberish;
    next: BigNumberish;
    contentObject: AddressLike;
    stake: BigNumberish;
    timeExpiring: BigNumberish;
  };

  export type ListingStructOutput = [
    previous: bigint,
    next: bigint,
    contentObject: string,
    stake: bigint,
    timeExpiring: bigint
  ] & {
    previous: bigint;
    next: bigint;
    contentObject: string;
    stake: bigint;
    timeExpiring: bigint;
  };
}

export interface ConsentFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "addDomain"
      | "adminRemoveListings"
      | "beaconAddress"
      | "blockContentObject"
      | "checkDomain"
      | "computeFee"
      | "createConsent"
      | "getGovernanceToken"
      | "getListingsBackward"
      | "getListingsForward"
      | "getRoleAdmin"
      | "getTagTotal"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "initializeTag"
      | "insertDownstream"
      | "insertUpstream"
      | "isStakingToken"
      | "listingDuration"
      | "maxTagsPerListing"
      | "moveUpstream"
      | "registerStakingToken"
      | "removeDomain"
      | "removeExpiredListings"
      | "removeListing"
      | "renounceRole"
      | "replaceExpiredListing"
      | "revokeRole"
      | "setListingDuration"
      | "setMaxTagsPerListing"
      | "supportsInterface"
      | "unblockContentObject"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddDomain"
      | "ConsentContractDeployed"
      | "Initialized"
      | "RankingUpdate"
      | "RemoveDomain"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "addDomain", values: [string]): string;
  encodeFunctionData(
    functionFragment: "adminRemoveListings",
    values: [string, AddressLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "beaconAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "blockContentObject",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "checkDomain", values: [string]): string;
  encodeFunctionData(
    functionFragment: "computeFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createConsent",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getGovernanceToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getListingsBackward",
    values: [string, AddressLike, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getListingsForward",
    values: [string, AddressLike, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTagTotal",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeTag",
    values: [string, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "insertDownstream",
    values: [string, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "insertUpstream",
    values: [string, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isStakingToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listingDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxTagsPerListing",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "moveUpstream",
    values: [string, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerStakingToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeDomain",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeExpiredListings",
    values: [string, AddressLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "removeListing",
    values: [string, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "replaceExpiredListing",
    values: [string, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setListingDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxTagsPerListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unblockContentObject",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addDomain", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "adminRemoveListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beaconAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blockContentObject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "computeFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGovernanceToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getListingsBackward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getListingsForward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTagTotal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeTag",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "insertDownstream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "insertUpstream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isStakingToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listingDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxTagsPerListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "moveUpstream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerStakingToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeExpiredListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "replaceExpiredListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setListingDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxTagsPerListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unblockContentObject",
    data: BytesLike
  ): Result;
}

export namespace AddDomainEvent {
  export type InputTuple = [domain: string];
  export type OutputTuple = [domain: string];
  export interface OutputObject {
    domain: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConsentContractDeployedEvent {
  export type InputTuple = [owner: AddressLike, consentAddress: AddressLike];
  export type OutputTuple = [owner: string, consentAddress: string];
  export interface OutputObject {
    owner: string;
    consentAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RankingUpdateEvent {
  export type InputTuple = [
    oldOccupant: AddressLike,
    newOccupant: AddressLike,
    stakingToken: AddressLike,
    tag: string,
    slot: BigNumberish
  ];
  export type OutputTuple = [
    oldOccupant: string,
    newOccupant: string,
    stakingToken: string,
    tag: string,
    slot: bigint
  ];
  export interface OutputObject {
    oldOccupant: string;
    newOccupant: string;
    stakingToken: string;
    tag: string;
    slot: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemoveDomainEvent {
  export type InputTuple = [domain: string];
  export type OutputTuple = [domain: string];
  export interface OutputObject {
    domain: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConsentFactory extends BaseContract {
  connect(runner?: ContractRunner | null): ConsentFactory;
  waitForDeployment(): Promise<this>;

  interface: ConsentFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  addDomain: TypedContractMethod<[domain: string], [void], "nonpayable">;

  adminRemoveListings: TypedContractMethod<
    [tag: string, stakingToken: AddressLike, removedSlots: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  beaconAddress: TypedContractMethod<[], [string], "view">;

  blockContentObject: TypedContractMethod<
    [stakingToken: AddressLike, contentAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  checkDomain: TypedContractMethod<[domain: string], [boolean], "view">;

  computeFee: TypedContractMethod<[_slot: BigNumberish], [bigint], "view">;

  createConsent: TypedContractMethod<
    [owner: AddressLike, baseURI: string],
    [void],
    "nonpayable"
  >;

  getGovernanceToken: TypedContractMethod<[], [string], "view">;

  getListingsBackward: TypedContractMethod<
    [
      tag: string,
      stakingToken: AddressLike,
      _startingSlot: BigNumberish,
      numSlots: BigNumberish,
      filterActive: boolean
    ],
    [[string[], IContentFactory.ListingStructOutput[]]],
    "view"
  >;

  getListingsForward: TypedContractMethod<
    [
      tag: string,
      stakingToken: AddressLike,
      _startingSlot: BigNumberish,
      numSlots: BigNumberish,
      filterActive: boolean
    ],
    [[string[], IContentFactory.ListingStructOutput[]]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTagTotal: TypedContractMethod<
    [tag: string, stakedToken: AddressLike],
    [bigint],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [_consentImpAddress: AddressLike, _governanceToken: AddressLike],
    [void],
    "nonpayable"
  >;

  initializeTag: TypedContractMethod<
    [tag: string, stakingToken: AddressLike, _newHead: BigNumberish],
    [void],
    "nonpayable"
  >;

  insertDownstream: TypedContractMethod<
    [
      tag: string,
      stakingToken: AddressLike,
      _existingSlot: BigNumberish,
      _newSlot: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  insertUpstream: TypedContractMethod<
    [
      tag: string,
      stakingToken: AddressLike,
      _newSlot: BigNumberish,
      _existingSlot: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  isStakingToken: TypedContractMethod<
    [tokenAddress: AddressLike],
    [boolean],
    "view"
  >;

  listingDuration: TypedContractMethod<[], [bigint], "view">;

  maxTagsPerListing: TypedContractMethod<[], [bigint], "view">;

  moveUpstream: TypedContractMethod<
    [
      tag: string,
      stakingToken: AddressLike,
      _newSlot: BigNumberish,
      _downstreamSlot: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  registerStakingToken: TypedContractMethod<
    [stakingToken: AddressLike],
    [void],
    "nonpayable"
  >;

  removeDomain: TypedContractMethod<[domain: string], [void], "nonpayable">;

  removeExpiredListings: TypedContractMethod<
    [tag: string, stakingToken: AddressLike, slots: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  removeListing: TypedContractMethod<
    [tag: string, stakingToken: AddressLike, removedSlot: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  replaceExpiredListing: TypedContractMethod<
    [tag: string, stakingToken: AddressLike, _slot: BigNumberish],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setListingDuration: TypedContractMethod<
    [listingDuration: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMaxTagsPerListing: TypedContractMethod<
    [maxTagsPerListing: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  unblockContentObject: TypedContractMethod<
    [stakingToken: AddressLike, contentAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addDomain"
  ): TypedContractMethod<[domain: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "adminRemoveListings"
  ): TypedContractMethod<
    [tag: string, stakingToken: AddressLike, removedSlots: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beaconAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "blockContentObject"
  ): TypedContractMethod<
    [stakingToken: AddressLike, contentAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkDomain"
  ): TypedContractMethod<[domain: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "computeFee"
  ): TypedContractMethod<[_slot: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "createConsent"
  ): TypedContractMethod<
    [owner: AddressLike, baseURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getGovernanceToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getListingsBackward"
  ): TypedContractMethod<
    [
      tag: string,
      stakingToken: AddressLike,
      _startingSlot: BigNumberish,
      numSlots: BigNumberish,
      filterActive: boolean
    ],
    [[string[], IContentFactory.ListingStructOutput[]]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getListingsForward"
  ): TypedContractMethod<
    [
      tag: string,
      stakingToken: AddressLike,
      _startingSlot: BigNumberish,
      numSlots: BigNumberish,
      filterActive: boolean
    ],
    [[string[], IContentFactory.ListingStructOutput[]]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTagTotal"
  ): TypedContractMethod<
    [tag: string, stakedToken: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_consentImpAddress: AddressLike, _governanceToken: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initializeTag"
  ): TypedContractMethod<
    [tag: string, stakingToken: AddressLike, _newHead: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "insertDownstream"
  ): TypedContractMethod<
    [
      tag: string,
      stakingToken: AddressLike,
      _existingSlot: BigNumberish,
      _newSlot: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "insertUpstream"
  ): TypedContractMethod<
    [
      tag: string,
      stakingToken: AddressLike,
      _newSlot: BigNumberish,
      _existingSlot: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isStakingToken"
  ): TypedContractMethod<[tokenAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "listingDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxTagsPerListing"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "moveUpstream"
  ): TypedContractMethod<
    [
      tag: string,
      stakingToken: AddressLike,
      _newSlot: BigNumberish,
      _downstreamSlot: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerStakingToken"
  ): TypedContractMethod<[stakingToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeDomain"
  ): TypedContractMethod<[domain: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeExpiredListings"
  ): TypedContractMethod<
    [tag: string, stakingToken: AddressLike, slots: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeListing"
  ): TypedContractMethod<
    [tag: string, stakingToken: AddressLike, removedSlot: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "replaceExpiredListing"
  ): TypedContractMethod<
    [tag: string, stakingToken: AddressLike, _slot: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setListingDuration"
  ): TypedContractMethod<[listingDuration: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxTagsPerListing"
  ): TypedContractMethod<
    [maxTagsPerListing: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unblockContentObject"
  ): TypedContractMethod<
    [stakingToken: AddressLike, contentAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AddDomain"
  ): TypedContractEvent<
    AddDomainEvent.InputTuple,
    AddDomainEvent.OutputTuple,
    AddDomainEvent.OutputObject
  >;
  getEvent(
    key: "ConsentContractDeployed"
  ): TypedContractEvent<
    ConsentContractDeployedEvent.InputTuple,
    ConsentContractDeployedEvent.OutputTuple,
    ConsentContractDeployedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "RankingUpdate"
  ): TypedContractEvent<
    RankingUpdateEvent.InputTuple,
    RankingUpdateEvent.OutputTuple,
    RankingUpdateEvent.OutputObject
  >;
  getEvent(
    key: "RemoveDomain"
  ): TypedContractEvent<
    RemoveDomainEvent.InputTuple,
    RemoveDomainEvent.OutputTuple,
    RemoveDomainEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "AddDomain(string)": TypedContractEvent<
      AddDomainEvent.InputTuple,
      AddDomainEvent.OutputTuple,
      AddDomainEvent.OutputObject
    >;
    AddDomain: TypedContractEvent<
      AddDomainEvent.InputTuple,
      AddDomainEvent.OutputTuple,
      AddDomainEvent.OutputObject
    >;

    "ConsentContractDeployed(address,address)": TypedContractEvent<
      ConsentContractDeployedEvent.InputTuple,
      ConsentContractDeployedEvent.OutputTuple,
      ConsentContractDeployedEvent.OutputObject
    >;
    ConsentContractDeployed: TypedContractEvent<
      ConsentContractDeployedEvent.InputTuple,
      ConsentContractDeployedEvent.OutputTuple,
      ConsentContractDeployedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "RankingUpdate(address,address,address,string,uint256)": TypedContractEvent<
      RankingUpdateEvent.InputTuple,
      RankingUpdateEvent.OutputTuple,
      RankingUpdateEvent.OutputObject
    >;
    RankingUpdate: TypedContractEvent<
      RankingUpdateEvent.InputTuple,
      RankingUpdateEvent.OutputTuple,
      RankingUpdateEvent.OutputObject
    >;

    "RemoveDomain(string)": TypedContractEvent<
      RemoveDomainEvent.InputTuple,
      RemoveDomainEvent.OutputTuple,
      RemoveDomainEvent.OutputObject
    >;
    RemoveDomain: TypedContractEvent<
      RemoveDomainEvent.InputTuple,
      RemoveDomainEvent.OutputTuple,
      RemoveDomainEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
