export enum EDataProvider {
  Etherscan = "Etherscan",
  Ankr = "Ankr",
  Blockvision = "Blockvision",
  Bluez = "Bluez",
  Poap = "Poap",
  EtherscanNative = "EtherscanNative",
  Expand = "Expand",
  Covalent = "Covalent",
  Alchemy = "Alchemy",
  Oklink = "Oklink",
  Solana = "Solana",
  Sui = "Sui",
  NftScan = "NftScan",
  Moralis = "Moralis",
  Matic = "Matic",
  Sim = "Sim",
  Polygon = "Polygon",
  DummySolana = "DummySolana",
  SpaceAndTime = "SpaceAndTime",
  Rarible = "Rarible",
}
