export enum EDataProvider {
  Etherscan = "Etherscan",
  Ankr = "Ankr",
  Poap = "Poap",
  EtherscanNative = "EtherscanNative",
  Covalent = "Covalent",
  Alchemy = "Alchemy",
  Oklink = "Oklink",
  Solana = "Solana",
  NftScan = "NftScan",
  Moralis = "Moralis",
  Matic = "Matic",
  Sim = "Sim",
  Polygon = "Polygon",
  DummySolana = "DummySolana",
}
