export enum EExternalApi {
  PrimaryControl = "Primary Control Chain",
  SecondaryControl = "Secondary Control Chain",
  AlchemyArbitrum = "Alchemy Arbitrum",
  AlchemyAstar = "Alechemy Astar",
  AlchemyMumbai = "Alchemy Mumbai",
  AlchemyOptimism = "Alchemy Optimism",
  AlchemyPolygon = "Alchemy Polygon",
  AlchemySolana = "Alchemy Solana",
  Ankr = "Ankr",
  CoinGecko = "Coin Gecko",
  Covalent = "Covalent",
  EtherscanEthereum = "Etherscan Ethereum",
  EtherscanPolygon = "Etherscan Polygon",
  EtherscanAvalanche = "Etherscan Avalanche",
  EtherscanBinance = "Etherscan Binance",
  EtherscanMoonbeam = "Etherscan Moonbeam",
  Moralis = "Moralis",
  NftScan = "NftScan",
  Oklink = "Oklink",
  POAP = "POAP",
  Polygon = "Polygon",
  Solana = "Solana",
  Unknown = "Unknown",
}
