/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as vesterSol from "./Vester.sol";
export type { vesterSol };
export type { DoodleToken } from "./DoodleToken";
export type { Snickerdoodle } from "./Snickerdoodle";
export type { WDoodleToken } from "./WDoodleToken";
