/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVotesUpgradeable } from "./IVotesUpgradeable";
export type { VotesUpgradeable } from "./VotesUpgradeable";
