/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface StorageHashInterface extends Interface {
  getFunction(
    nameOrSignature: "ContentFactory" | "ContentObject" | "ERC7529" | "Pausable"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ContentFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ContentObject",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ERC7529", values?: undefined): string;
  encodeFunctionData(functionFragment: "Pausable", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "ContentFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ContentObject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ERC7529", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "Pausable", data: BytesLike): Result;
}

export interface StorageHash extends BaseContract {
  connect(runner?: ContractRunner | null): StorageHash;
  waitForDeployment(): Promise<this>;

  interface: StorageHashInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ContentFactory: TypedContractMethod<[], [string], "view">;

  ContentObject: TypedContractMethod<[], [string], "view">;

  ERC7529: TypedContractMethod<[], [string], "view">;

  Pausable: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ContentFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ContentObject"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ERC7529"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "Pausable"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
