const errorCodes = {
  AccountIndexingError: "ERR_ACCOUNT_INDEXER",
  AjaxError: "ERR_AJAX",
  BlockchainProviderError: "ERR_BLOCKCHAIN_PROVIDER",
  ConsentContractRepositoryError: "CONSENT_CONTRACT_REPOSITORY_ERROR",
  ConsentContractError: "CONSENT_CONTRACT_ERROR",
  ConsentError: "ERR_NO_CONSENT_GIVEN",
  ConsentFactoryContractError: "CONSENT_FACTORY_CONTRACT_ERROR",
  CrumbsContractError: "CRUMBS_CONTRACT_ERROR",
  DatabaseError: "ERR_DATABASE",
  DataWalletLockedError: "ERR_DATA_WALLET_LOCKED",
  InvalidParametersError: "INVALID_PARAMETERS_ERROR",
  InvalidSignatureError: "ERR_INVALID_SIGNATURE",
  IPFSError: "ERR_IPFS",
  MinimalForwarderContractError: "ERR_MINIMAL_FORWARDER_CONTRACT",
  JWKSError: "ERR_JWKS",
  PersistenceError: "ERR_PERSISTENCE",
  ProviderRpcError: "PROVIDER_RPC_ERROR",
  MissingWalletDataTypeError: "ERR_MISSING_WALLET_DATA_TYPE",
  PermissionError: "ERR_PERMISSION",
  QueryExpiredError: "ERR_QUERY_EXPIRED",
  MissingASTError: "ERR_MISSING_AST",
  ParserTypeNotImplementedError: "ERR_PARSER_TYPE_NOT_IMPLEMENTED",
  RewardsFactoryError: "ERR_REWARDS_FACTORY",
  ServerRewardError: "ERR_SERVER_REWARD",
  TransactionResponseError: "ERR_TRANSACTION_RESPONSE",
  SiftContractError: "ERR_SIFT_CONTRACT",
  UnauthorizedError: "ERR_UNAUTHORIZED",
  UninitializedError: "ERR_UNINITIALIZED",
  UnsupportedLanguageError: "ERR_UNSUPPORTED_LANGUAGE",
  GasPriceError: "ERR_GAS_PRICE",
};

export default errorCodes;
