const errorCodes = {
  AcceptPaymentError: "01",
  AjaxError: "02",
  BalancesUnavailableError: "03",
  BlockchainUnavailableError: "04",
  ERC20ContractError: "05",
  GatewayActivationError: "06",
  GatewayAuthorizationDeniedError: "07",
  GatewayConnectorError: "08",
  GatewayValidationError: "09",
  GovernanceSignerUnavailableError: "10",
  HypernetGovernorContractError: "11",
  InsufficientBalanceError: "12",
  InvalidParametersError: "13",
  InvalidPaymentError: "14",
  InvalidPaymentIdError: "15",
  LogicalError: "16",
  MessagingError: "17",
  ConsentContractError: "18",
  OfferMismatchError: "19",
  PaymentCreationError: "20",
  PaymentFinalizeError: "21",
  PaymentStakeError: "22",
  PersistenceError: "23",
  PostmateError: "24",
  ProviderRpcError: "25",
  ProxyError: "26",
  ConsentFactoryContractError: "27",
  RegistryPermissionError: "28",
  RenderError: "29",
  RouterChannelUnknownError: "30",
  RouterUnauthorizedError: "31",
  TransferCreationError: "32",
  TransferResolutionError: "33",
  VectorError: "34",
  InactiveGatewayError: "35",
  BatchModuleContractError: "36",
  LazyMintModuleContractError: "37",
  IPFSUnavailableError: "38",
  GasPriceError: "39",
  TransactionNotImplementedError: "40",
  TransactionServerError: "41",
  TransactionTimeoutError: "42",
  TransactionUnknownError: "43",
  TransactionUnsupportedOperationError: "44",
};

export default errorCodes;
