export const ProductCategories = [
  "Home Improvement",
  "Electronics",
  "Outdoors",
  "Hair Care",
  "unknown",
  "Automotive Accessories",
  "Phone Accessories",
  "Fashion",
  "Books",
  "Sports",
  "Food & Grocery",
  "Health & Personal Care",
  "Toys & Games",
  "Office Products",
  "Baby",
  "Pet Supplies",
  "Computers",
];
