/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC7529,
  IERC7529Interface,
} from "../../../contracts/erc7529/IERC7529";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "domain",
        type: "string",
      },
    ],
    name: "AddDomain",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "domain",
        type: "string",
      },
    ],
    name: "RemoveDomain",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "domain",
        type: "string",
      },
    ],
    name: "checkDomain",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IERC7529__factory {
  static readonly abi = _abi;
  static createInterface(): IERC7529Interface {
    return new Interface(_abi) as IERC7529Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): IERC7529 {
    return new Contract(address, _abi, runner) as unknown as IERC7529;
  }
}
