/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ContentObjectUpgradeable,
  ContentObjectUpgradeableInterface,
} from "../../../contracts/recomender/ContentObjectUpgradeable";

const _abi = [
  {
    inputs: [],
    name: "InvalidInitialization",
    type: "error",
  },
  {
    inputs: [],
    name: "NotInitializing",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "version",
        type: "uint64",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    inputs: [],
    name: "getContentAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "stakingToken",
        type: "address",
      },
    ],
    name: "getNumberOfStakedTags",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "stakingToken",
        type: "address",
      },
    ],
    name: "getTagArray",
    outputs: [
      {
        components: [
          {
            internalType: "string",
            name: "tag",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "slot",
            type: "uint256",
          },
        ],
        internalType: "struct IContentObject.Tag[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "tag",
        type: "string",
      },
      {
        internalType: "address",
        name: "stakingToken",
        type: "address",
      },
    ],
    name: "tagIndices",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ContentObjectUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): ContentObjectUpgradeableInterface {
    return new Interface(_abi) as ContentObjectUpgradeableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ContentObjectUpgradeable {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ContentObjectUpgradeable;
  }
}
