export enum EModalSelectors {
  ACCOUNT_UNLINKED,
  PHANTOM_LINKING_STEPS,
  SUI_LINKING_STEPS,
  CUSTOMIZABLE_MODAL,
  LEAVE_AUDIENCE_MODAL,
  REWARD_DETAIL_MODAL,
  OTP_MODAL,
  CONFIRMATION_MODAL,
}
