export enum EModalSelectors {
  OTP_MODAL,
  CONFIRMATION_MODAL,
  AIRDROP_DETAIL_MODAL,
  NFT_DETAIL_MODAL,
  QUESTIONNAIRE_MODAL,
  SHARE_QUESTIONNAIRE_MODAL,
  ANSWERED_QUESTIONNAIRE_MODAL,
  BRAND_PERMISSIONS_MODAL,
  OFFER_MODAL,
}
