export enum EModalSelectors {
  ACCOUNT_UNLINKED,
  PHANTOM_LINKING_STEPS,
  VIEW_ACCOUNT_DETAILS,
  PERMISSION_SELECTION,
  MANAGE_PERMISSIONS,
  CONFIRMATION_MODAL,
  CUSTOMIZABLE_MODAL,
  LEAVE_COHORT_MODAL,
  SUBSCRIPTION_SUCCESS_MODAL,
  SUBSCRIPTION_CONFIRMATION_MODAL,
  REWARD_DETAIL_MODAL,
}
