/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as draftIerc6093Sol from "./draft-IERC6093.sol";
export type { draftIerc6093Sol };
export type { IERC1271 } from "./IERC1271";
export type { IERC4906 } from "./IERC4906";
export type { IERC5267 } from "./IERC5267";
export type { IERC5805 } from "./IERC5805";
export type { IERC6372 } from "./IERC6372";
