import { makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles((theme) => ({
  title: {
    fontFamily: "Shrikhand",
    fontSize: 36,
    fontWeight: 400,
    color: "#232039",
  },
  description: {
    fontFamily: "Space Grotesk",
    fontWeight: 400,
    fontSize: 18,
    lineHeight: "23px",
  },
  formLabel: {
    fontSize: 16,
    fontWeight: 500,
    fontFamily: "Space Grotesk",
    color: "#232039",
  },
  input: {
    width: 330,
    height: 55,
    border: "1px solid #D9D9D9",
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 500,
    color: "#929292",
  },
  errorMessage: {
    margin: 0,
    marginLeft: 14,
    marginRight: 14,
    color: "#f44336",
    fontSize: "0.75rem",
    marginTop: 3,
    textAlign: "left",
    fontWeight: 400,
    lineHeight: 1.66,
    letterSpacing: "0.03333em",
  },
  artboardImageContainer: {},
  buttonContainer: {
    display: "flex",
    justifyContent: "flex-end",
    margin: 20,
  },
  socialLoginTitle: {
    fontFamily: "Space Grotesk",
    fontWeight: 700,
    fontSize: 20,
    color: "#232039",
  },
  googleButton: {
    width: "330px !important",
    height: "52px !important",
    border: "1px solid #D9D9D9 !important",
    borderRadius: "8px !important",
    fontFamily: "'Space Grotesk', sans-serif !important",
    fontSize: "14px !important",
    fontWeight: 500,
    color: "black !important",
    letterSpacing: "1px !important",
    justifyContent: "center",
  },
  selectInput: {
    width: 330,
    height: 55,
    border: "1px solid #D9D9D9",
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 500,
    "& .MuiSelect-nativeInput": {
      color: "#000 !important",
    },
    "& .MuiSelect-select:focus": {
      backgroundColor: "#fff !important",
    },
  },
  itemName: {
    fontFamily: "'Space Grotesk'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "24px",
    lineHeight: "30px",
    textAlign: "center",
    textTransform: "uppercase",
  },
}));
