apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: protocol-iframe-deployment
  namespace: {{ .Values.ENV }}
  labels:
    app: protocol-iframe
    tier: backend
spec:
  selector:
    matchLabels:
      app: protocol-iframe
      tier: backend
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: protocol-iframe
        tier: backend
    spec:
      imagePullSecrets:
      - name: artifact-registry
      containers:
      - name: protocol-iframe
        image: {{ .Values.ProtocolIframe.Image.Repo}}:{{ .Values.ProtocolIframe.Image.Tag }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "500m"

        ports:
        - containerPort: 80
