apiVersion: v1
kind: Service
metadata:
  name: protocol-iframe
  namespace: {{ .Values.ENV }}
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"protocol-iframe-backendconfig"}}'
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: protocol-iframe
    tier: backend
spec:
  type: ClusterIP
  ports:
    - name: protocol-iframe
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: protocol-iframe
    tier: backend
