apiVersion: v1
kind: Service
metadata:
  name: insight-platform-protocol
  labels:
    app: insight-platform-protocol
    tier: backend
spec:
  type: ClusterIP
  ports:
  - name: protocol
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: insight-platform-protocol
    tier: backend