/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as snickerdoodleTimeLockSol from "./SnickerdoodleTimeLock.sol";
export type { snickerdoodleTimeLockSol };
export type { SnickerdoodleGovernor } from "./SnickerdoodleGovernor";
