import { makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles((theme) => ({
  container: {
    "& .MuiDialog-paper": {
      borderRadius: 12,
    },
  },
  primaryButton: {
    textTransform: "unset",
    padding: "12px 46px 10px 12px",
    boxShadow: "3px 3px 0px 0px rgb(0 0 0)",
    background: "#8079B4",
    color: "#fff",
    borderColor: "#000",
    borderRadius: 0,
    "&:hover": {
      backgroundColor: "#8079B4",
      borderColor: "#000",
    },
  },
  primaryButtonIcon: {
    position: "absolute",
    top: 4,
    right: 4,
    width: 14,
  },
  buttonText: {
    fontFamily: "Space Grotesk",
    fontWeight: 500,
    fontSize: 10,
    color: "#222137",
    textDecoration: "underline",
    textTransform: "capitalize",
  },
  subtitle: {
    fontFamily: "Space Grotesk",
    fontWeight: 300,
    fontSize: 12,
    color: "#222137",
  },
  footerText: {
    fontFamily: "Space Grotesk",
    fontWeight: 500,
    fontSize: 9,
    color: "#8D8B9E",
  },
  accountSectionContainer: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    backgroundColor: "white",
  },
  accountInfoText: {
    fontFamily: "'Space Grotesk'",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "160%",
    color: "#212121",
    marginRight: 20,
  },
  account: {
    marginLeft: 6,
    fontFamily: "'Space Grotesk'",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "11px",
    lineHeight: "160%",
    color: "#212121",
  },
  changeRecievingAccountText: {
    fontFamily: "'Space Grotesk'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "14px",
    lineHeight: "24px",
    textDecorationLine: "underline",
    color: "#181818",
  },
  changeAccountDescription: {
    marginTop: 6,
    fontFamily: "'Space Grotesk'",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "11px",
    lineHeight: "14px",
    color: "#8D8B9E",
  },
}));
