/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as snickerdoodleTimeLockSol from "./SnickerdoodleTimeLock.sol";
export { SnickerdoodleGovernor__factory } from "./SnickerdoodleGovernor__factory";
