/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Consent__factory } from "./Consent__factory";
export { ConsentFactory__factory } from "./ConsentFactory__factory";
export { IConsent__factory } from "./IConsent__factory";
export { IConsentFactory__factory } from "./IConsentFactory__factory";
