import { makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles((theme) => ({
  name: {
    fontFamily: "'Roboto'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "14px",
    lineHeight: "133.4%",
    color: "#424242",
    whiteSpace: "initial",
    overflow: "hidden",
    textOverflow: "ellipsis",
    display: "-webkit-box",
    WebkitLineClamp: 1,
    WebkitBoxOrient: "vertical",
  },
  image: {
    aspectRatio: "1",
    objectFit: "cover",
    width: 69,
    height: 69,
    borderRadius: "50%",
  },
  description: {
    fontFamily: "'Roboto'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "12.0627px",
    lineHeight: "133.4%",
    color: "rgba(35, 32, 57, 0.87)",
    whiteSpace: "initial",
    overflow: "hidden",
    textOverflow: "ellipsis",
    display: "-webkit-box",
    WebkitLineClamp: 1,
    WebkitBoxOrient: "vertical",
  },
  earnedText: {
    fontFamily: "'Roboto'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "12px",
    lineHeight: "161%",
    color: "#616161",
  },
  leftText: {
    fontFamily: "'Roboto'",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "12px",
    lineHeight: "161%",
    color: "#D32F2F",
  },
  imageLoader: {
    width: "100%",
    aspectRatio: "4/3",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  brokenImageIcon: {
    fontSize: 60,
    color: "#D9D9D9",
  },
  leaveButton: {
    fontFamily: "'Roboto'",
    fontStyle: "normal",
    textAlign: "center",
    fontWeight: 500,
    fontSize: "14.05px",
    lineHeight: "16px",
    textDecorationLine: "underline",
    color: "#D32F2F",
    cursor: "pointer",
  },
  rewardText: {
    fontFamily: "'Roboto'",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "12px",
    lineHeight: "14px",
    color: "#616161",
  },
  subscribedText: {
    fontFamily: "'Roboto'",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "12px",
    lineHeight: "13px",
    display: "flex",
    alignItems: "center",
    color: "#54A858",
  },
}));
