name: Extension Build

on:
  push:
    branches: sandbox/*
env:
  GITHUB_SHA: ${{ github.sha }} 
  GITHUB_REF: ${{ github.ref }} 
jobs:
  build_extension:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: scrapping coin list
        run: |-
          python infra/scrapper/coin_list_gen.py 
      - name: scrapping price list
        run: |-
          python infra/scrapper/coin_price_gen.py
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: Identifier Fetching
        id: identifier
        run: |-
          JIRA_TICKET=$(echo $GITHUB_REF | grep -Eo '[A-Z0-9]*-[0-9]*' | awk '{print tolower($0)}')
          GKE_CLUSTER=$(gcloud container clusters list --format="csv(name)" | grep $JIRA_TICKET)  
          output=$(echo $GKE_CLUSTER | sed "s/sdl-cluster-//")
          echo "::set-output name=identifier::$output"
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |-
          JIRA_TICKET=$(echo $GITHUB_REF | grep -Eo '[A-Za-z0-9]*-[0-9]*' | awk '{print tolower($0)}')
          cd packages/browserExtension && YARN_CHECKSUM_BEHAVIOR=update yarn && yarn precompile && yarn compile && __REQUEST_FOR_DATA_EVENT_FREQ__=4000 __CONTROL_CHAIN_ID__=31337 __ONBOARDING_URL__="https://datawallet.${JIRA_TICKET}.snickerdoodle.dev/" __ACCOUNT_COOKIE_URL__='https://snickerdoodlelabs.io/' __SUPPORTED_CHAINS__='80001,43113,1,137,43114' __IPFS_FETCH_BASE_URL__='https://ipfs-gateway.snickerdoodle.dev/ipfs/' __DEFAULT_INSIGHT_PLATFORM_BASE_URL__="https://insight-api.${JIRA_TICKET}.snickerdoodle.dev/v0/" __DEV_CHAIN_PROVIDER_URL__="https://doodlechain.${JIRA_TICKET}.snickerdoodle.dev" __PRIMARY_INFURA_KEY__="a8ae124ed6aa44bb97a7166cda30f1bc" __COVALENT_API_KEY__='' __MORALIS_API_KEY__='' __NFTSCAN_API_KEY__='' __POAP_API_KEY__='' __OKLINK_API_KEY__='' __ANKR_API_KEY__='' __ALCHEMY_ARBITRUM_API_KEY__="" __ALCHEMY_ASTAR_API_KEY__="" __ALCHEMY_MUMBAI_API_KEY__="" __ALCHEMY_OPTIMISM_API_KEY__="" __ALCHEMY_POLYGON_API_KEY__="" __ALCHEMY_SOLANA_API_KEY__="" __ALCHEMY_SOLANA_TESTNET_API_KEY__="" __ALCHEMY_SOLANA_TESTNET_API_KEY__="" __ETHERSCAN_ETHEREUM_API_KEY__="" __ETHERSCAN_POLYGON_API_KEY__="" __ETHERSCAN_AVALANCHE_API_KEY__="" __ETHERSCAN_BINANCE_API_KEY__="" __ETHERSCAN_MOONBEAM_API_KEY__="" __ETHERSCAN_OPTIMISM_API_KEY__='' __ETHERSCAN_ARBITRUM_API_KEY__='' __ETHERSCAN_GNOSIS_API_KEY__='' __ETHERSCAN_FUJI_API_KEY__='' __PRIMARY_INFURA_KEY__='' __SECONDARY_INFURA_KEY__='' __DOMAIN_FILTER__='(localhost|chrome:\/\/)' __DNS_SERVER_ADDRESS__='' __GOOGLE_CLOUD_BUCKET__="${{ steps.identifier.outputs.identifier }}-sdl-dw" PRIMARY_INFURA_KEY="a6271a49218848a7ad939ee62d225914"  IFRAME_URL="http://localhost:9010"   node utils/build.cjs $JIRA_TICKET 
          
      - uses: actions/upload-artifact@v3
        with:
          name: sandbox-extension
          path: packages/browserExtension/build-*
