name: Extension Build

on:
  push:
    branches: sandbox/*
env:
  GITHUB_SHA: ${{ github.sha }} 
  GITHUB_REF: ${{ github.ref }} 
jobs:
  build_extension:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |-
          JIRA_TICKET=$(echo $GITHUB_REF | grep -Eo '[A-Za-z0-9]*-[0-9]*' | awk '{print tolower($0)}')
          cd packages/browserExtension && yarn && yarn precompile && yarn compile && __REQUEST_FOR_DATA_EVENT_FREQ__=4000 __CONTROL_CHAIN_ID__=31337 __ONBOARDING_URL__="https://datawallet.${JIRA_TICKET}.snickerdoodle.dev/" __ACCOUNT_COOKIE_URL__='https://snickerdoodlelabs.io/' __SUPPORTED_CHAINS__='80001,43113,1,137,43114' __IPFS_FETCH_BASE_URL__='https://ipfs-gateway.snickerdoodle.dev/ipfs/' __DEFAULT_INSIGHT_PLATFORM_BASE_URL__="https://insight-api.${JIRA_TICKET}.snickerdoodle.dev/v0/" __CERAMIC_NODE_URL__='https://ceramic.snickerdoodle.dev/' __CONTROL_CHAIN_PROVIDER_URL__="https://doodlechain.${JIRA_TICKET}.snickerdoodle.dev" __COVALENT_API_KEY__='' __MORALIS_API_KEY__='' __NFTSCAN_API_KEY__='' __DOMAIN_FILTER__='(localhost|chrome:\/\/)' __DNS_SERVER_ADDRESS__='' node utils/build.cjs $JIRA_TICKET 
          
      - uses: actions/upload-artifact@v3
        with:
          name: sandbox-extension
          path: packages/browserExtension/build-*
