name: Build and Push to GCR

on:
  push:
    branches: main


env:
  GITHUB_SHA: ${{ github.sha }} 
  GITHUB_REF: ${{ github.ref }} 
  IMAGE: insight-platform
  REGISTRY_HOSTNAME: gcr.io
  GAR_LOCATION: us-central1
  GKE_CLUSTER: sdl-cluster-prod-qkppf
  GKE_ZONE: us-central1-a
  PROJECT_ID: snickerdoodle-insight-stackdev


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.PROD_GCP_CREDENTIALS }}'
    - name: Identifier Fetching
      id: identifier
      run: |-
        JIRA_TICKET=prod
        GKE_CLUSTER=$(gcloud container clusters list --format="csv(name)" | grep $JIRA_TICKET)  
        output=$(echo $GKE_CLUSTER | sed "s/sdl-cluster-//")
        echo "::set-output name=identifier::$output"
        
        
    # Setup gcloud CLI
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        

    - name: Docker configuration
      run: |-
        gcloud --quiet auth configure-docker $GAR_LOCATION-docker.pkg.dev


    - name: Build protocol base
      run: |-
        docker build \
          --tag "snickerdoodlelabs/protocol-docker-base:$GITHUB_SHA" \
          -f ./packages/docker/Dockerfile \
          .

    - name: Build Protocol SPA
      run: |-
        docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/insight-platform/protocol:$GITHUB_SHA" \
          --build-arg DOMAIN="datawallet.snickerdoodle.com" \
          --build-arg CONTROL_CHAIN_ID=43113 \
          --build-arg BUILD_ENV=prod \
          --build-arg INFURA_ID=72827ccd538446f2a20e35a632664c52 \
          --build-arg GAPI_CLIENT_ID=332580693256-mifj8rkovvlc332n8gtllpdl93e6nvio.apps.googleusercontent.com \
          --build-arg IPFS_FETCH_BASE_URL="https://ipfs-gateway.snickerdoodle.com/ipfs/" \
          --build-arg GOOGLE_CLOUD_BUCKET=${{ steps.identifier.outputs.identifier }}-sdl-dw \
          --build-arg GA_TRACKING_ID="UA-219658390-3" \
          --build-arg IFRAME_URL="https://iframe.snickerdoodle.com" \
          --build-arg BASE_TAG="$GITHUB_SHA" \
          -f ./packages/extension-onboarding/Dockerfile \
          .

    - name: Publish Protocol SPA
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/insight-platform/protocol:$GITHUB_SHA"


    - name: Build Static Web Integration
      run: |-
        JIRA_TICKET=$(echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})" | grep -Eo '[A-Za-z0-9]*-[0-9]*' | awk '{print tolower($0)}')
      
        docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/insight-platform/protocol-static-web-integration:$GITHUB_SHA" \
          --build-arg BASE_TAG="$GITHUB_SHA" \
          -f ./packages/static-web-integration/Dockerfile \
          .
    - name: Publish Static Web Integration
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/insight-platform/protocol-static-web-integration:$GITHUB_SHA"

    - name: Build Protocol Iframe
      run: |-
        JIRA_TICKET=$(echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})" | grep -Eo '[A-Za-z0-9]*-[0-9]*' | awk '{print tolower($0)}')
      
        docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/insight-platform/protocol-iframe:$GITHUB_SHA" \
          --build-arg DEFAULT_INSIGHT_PLATFORM_BASE_URL="https://insight-api.snickerdoodle.com/v0/" \
          --build-arg REQUEST_FOR_DATA_POLLING_INTERVAL=300000 \
          --build-arg CONTROL_CHAIN_ID=43113 \
          --build-arg IPFS_FETCH_BASE_URL=https://ipfs-gateway.snickerdoodle.com/ipfs/ \
          --build-arg BASE_TAG="$GITHUB_SHA" \
          --build-arg PRIMARY_INFURA_KEY=8497d7f3186c4edcaaff8838478c634d \
          --build-arg ANKR_API_KEY=f50d7a208124e6a6df731477fdc9ef420ce59769ced1e9339318a383365cb6a1 \
          --build-arg BLUEZ_API_KEY=aed4aab2cbc573bbf8e7c6b448c916e5 \
          --build-arg COVALENT_API_KEY=cqt_wFfHg4vmGKyMxGvPPxdHm8VCDPCY \
          --build-arg POAP_API_KEY=wInY1o7pH1yAGBYKcbz0HUIXVHv2gjNTg4v7OQ70hykVdgKlXU3g7GGaajmEarYIX4jxCwm55Oim7kYZeML6wfLJAsm7MzdvlH1k0mKFpTRLXX1AXDIwVQer51SMeuQm \
          --build-arg ALCHEMY_ARBITRUM_API_KEY=_G9cUGHUQqvD2ro5zDaTAFXeaTcNgQiF \
          --build-arg ALCHEMY_ASTAR_API_KEY=Tk2NcwnHwrmRvzZCkqgSr6fOYIgH7xh7 \
          --build-arg ALCHEMY_MUMBAI_API_KEY=UA7tIJ6CdCE1351h24CQUE-MNCIV3DSf \
          --build-arg ALCHEMY_OPTIMISM_API_KEY=f3mMgv03KKiX8h-pgOc9ZZyu7F9ECcHG \
          --build-arg ALCHEMY_POLYGON_API_KEY=el_YkQK0DMQqqGlgXPO5gm8g6WmpdNfX \
          --build-arg ALCHEMY_SOLANA_API_KEY=pci9xZCiwGcS1-_jWTzi2Z1LqAA7Ikeg \
          --build-arg ALCHEMY_SOLANA_TESTNET_API_KEY=K1r7FB6hBm0QyXy4qyUa0xHun1Dmkc05 \
          -f ./packages/iframe/Dockerfile \
          .
    - name: Publish Protocol Iframe
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/insight-platform/protocol-iframe:$GITHUB_SHA"


  deploy:
    name: Deploy
    needs: [ setup-build-publish-deploy ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2


    # Setup gcloud CLI
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.PROD_GCP_CREDENTIALS }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    - name: Deploy to GCR
      run: |-
        gcloud components install gke-gcloud-auth-plugin
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        
        chmod 700 get_helm.sh
        ./get_helm.sh
        cd infra/
      
        helm upgrade -f ./insight-platform-protocol/values.yaml --install --reuse-values -n prod  --set ProtocolIframe.Image.Tag=$GITHUB_SHA --set InsightPlatformProtocol.Image.Tag=$GITHUB_SHA --set ProtocolStaticWebIntegration.Image.Tag=$GITHUB_SHA  insight-platform-protocol ./insight-platform-protocol

