name: Build and Push to GCR

on:
  push:
    branches: develop


env:
  GITHUB_SHA: ${{ github.sha }} 
  GITHUB_REF: ${{ github.ref }} 
  IMAGE: insight-platform
  REGISTRY_HOSTNAME: gcr.io
  GAR_LOCATION: us-central1
  GKE_CLUSTER: test-cluster-defaultkxomm
  GKE_ZONE: us-central1-a
  PROJECT_ID: snickerdoodle-insight-stackdev


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        

    - name: Docker configuration
      run: |-
        gcloud --quiet auth configure-docker $GAR_LOCATION-docker.pkg.dev
        
    - name: Build protocol
      run: |-
      
        docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/insight-platform/protocol:$GITHUB_SHA" \
          --build-arg DOMAIN="extension.dev.snickerdoodle.dev" \
          -f ./packages/extension-onboarding/Dockerfile \
          .
  
    # Push the Docker image to Google Artifact Registry
    - name: Publish protocol
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/insight-platform/protocol:$GITHUB_SHA"
        

#    Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials & Deploy protocol
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
        kubectl set image deployment/insight-platform-insight-platform-protocol-deployment insight-platform-protocol=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/insight-platform/protocol:$GITHUB_SHA
