export enum EPaths {
  ONBOARDING = "/onboarding",
  // ONBOARDING_WELCOME = "/onboarding/welcome",
  ONBOARDING_LINK_ACCOUNT = "/onboarding/link-account",
  ONBOARDING_BUILD_PROFILE = "/onboarding/build-profile",
  // ONBOARDING_VIEW_DATA = "/onboarding/view-data",
  ONBOARDING_OPT_IN = "/onboarding/opt-in",
  HOME = "/",
  CAMPAIGNS = "/campaigns",
  MY_REWARDS = "/my-rewards",
  CAMPAIGN_SETTINGS = "/settings/campaigns",
  MARKETPLACE_CAMPAIGNS = "/campaigns/marketplace",
  MARKETPLACE_COLLECTION = "/rewards/marketplace/:brand",
  MARKETPLACE_REWARD = "/rewards/marketplace/reward",
  SETTINGS = "/settings",
  WEB3_SETTINGS = "/settings/web3",
  WEB2_SETTINGS = "/settings/web2",
  DATA_PERMISSIONS_SETTING = "/settings/data-permissions",
  SCAM_FILTER_SETTINGS = "/settings/scam-filter",
  TOKENS = "/data-dashboard/tokens",
  NFTS = "/data-dashboard/nfts",
  BROWSER_ACTIVITY = "/data-dashboard/browser-activity",
  SOCIAL_MEDIA_DATA = "/data-dashboard/social-media-data",
  PERSONAL_INFO = "/data-dashboard/personal-info",
  NFT_DETAIL = "/data-dashboard/nfts/detail",
}
