export enum EPaths {
  ONBOARDING = "/onboarding",
  ONBOARDING_LINK_ACCOUNT = "/onboarding/link-account",
  ONBOARDING_BUILD_PROFILE = "/onboarding/build-profile",
  ONBOARDING_OPT_IN = "/onboarding/opt-in",
  ONBOARDING_PERMISSION_SELECTION = "/onboarding/permission-selection",
  ONBOARDING_TAG_SELECTION = "/onboarding/tag-selection",
  HOME = "/",
  CAMPAIGNS = "/campaigns",
  MY_REWARDS = "/my-rewards",
  MARKETPLACE_CAMPAIGNS = "/campaigns/marketplace",
  MARKETPLACE_COLLECTION = "/rewards/marketplace/:brand",
  MARKETPLACE_REWARD = "/rewards/marketplace/reward",
  SETTINGS = "/settings",
  WEB3_SETTINGS = "/settings/web3",
  WEB2_SETTINGS = "/settings/web2",
  REWARDS_SUBSCRIPTIONS = "/settings/rewards-subscriptions",
  REWARDS_SUBSCRIPTION_DETAIL = "/settings/rewards-subscriptions/detail",
  DATA_PERMISSIONS_SETTING = "/settings/data-permissions",
  SCAM_FILTER_SETTINGS = "/settings/scam-filter",
  TOKENS = "/data-dashboard/tokens",
  NFTS = "/data-dashboard/nfts",
  BROWSER_ACTIVITY = "/data-dashboard/browser-activity",
  PERSONAL_INFO = "/data-dashboard/personal-info",
  NFT_DETAIL = "/data-dashboard/nfts/detail",
}
