export enum EPathsV2 {
  HOME = "/",
  BRAND = "/brand/:consentContractAddress",
  COOKIE_VAULT = "/cookie-vault",
  TRUSTED_BRANDS = "/trusted-brands",
  OFFERS = "/offers",
  ONBOARDING = "/onboarding",
  SETTINGS = "/settings",
  DATA_DASHBOARD = "/data-dashboard",
  TOKENS = "/data-dashboard/tokens",
  NFTS = "/data-dashboard/nfts",
  AIRDROPS = "/data-dashboard/airdrops",
  POAP_NFTS = "/data-dashboard/poap-nfts",
  BROWSER_ACTIVITY = "/data-dashboard/browser-activity",
  SOCIAL_MEDIA_DATA = "/data-dashboard/social-media-data",
  TRANSACTION_HISTORY = "/data-dashboard/transaction-history",
}
